# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{riot}
  s.version = "0.11.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin 'Gus' Knowlden"]
  s.date = %q{2010-06-14}
  s.description = %q{An extremely fast, expressive, and context-driven unit-testing framework. A replacement for all other testing frameworks. Protest the slow test.}
  s.email = %q{gus@gusg.us}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO.markdown",
     "VERSION",
     "lib/riot.rb",
     "lib/riot/assertion.rb",
     "lib/riot/assertion_macro.rb",
     "lib/riot/assertion_macros/any.rb",
     "lib/riot/assertion_macros/assigns.rb",
     "lib/riot/assertion_macros/empty.rb",
     "lib/riot/assertion_macros/equals.rb",
     "lib/riot/assertion_macros/equivalent_to.rb",
     "lib/riot/assertion_macros/exists.rb",
     "lib/riot/assertion_macros/includes.rb",
     "lib/riot/assertion_macros/kind_of.rb",
     "lib/riot/assertion_macros/matches.rb",
     "lib/riot/assertion_macros/nil.rb",
     "lib/riot/assertion_macros/not_borat.rb",
     "lib/riot/assertion_macros/raises.rb",
     "lib/riot/assertion_macros/respond_to.rb",
     "lib/riot/assertion_macros/same_elements.rb",
     "lib/riot/assertion_macros/size.rb",
     "lib/riot/context.rb",
     "lib/riot/message.rb",
     "lib/riot/middleware.rb",
     "lib/riot/reporter.rb",
     "lib/riot/rr.rb",
     "lib/riot/runnable.rb",
     "lib/riot/situation.rb",
     "riot.gemspec",
     "test/benchmark/colorize.rb",
     "test/benchmark/message_concatenation.rb",
     "test/benchmark/riot_vs_minitest.rb",
     "test/benchmark/same_elements_vs_set.rb",
     "test/benchmark/simple_context_and_assertions.rb",
     "test/core/assertion_macro_test.rb",
     "test/core/assertion_macros/any_test.rb",
     "test/core/assertion_macros/assigns_test.rb",
     "test/core/assertion_macros/empty_test.rb",
     "test/core/assertion_macros/equals_test.rb",
     "test/core/assertion_macros/equivalent_to_test.rb",
     "test/core/assertion_macros/exists_test.rb",
     "test/core/assertion_macros/includes_test.rb",
     "test/core/assertion_macros/kind_of_test.rb",
     "test/core/assertion_macros/matching_test.rb",
     "test/core/assertion_macros/nil_test.rb",
     "test/core/assertion_macros/not_borat_test.rb",
     "test/core/assertion_macros/raises_test.rb",
     "test/core/assertion_macros/respond_to_test.rb",
     "test/core/assertion_macros/same_elements_test.rb",
     "test/core/assertion_macros/size_test.rb",
     "test/core/assertion_test.rb",
     "test/core/chained_context_middleware_test.rb",
     "test/core/context_middleware_test.rb",
     "test/core/context_test.rb",
     "test/core/context_with_options_test.rb",
     "test/core/message_test.rb",
     "test/core/report_test.rb",
     "test/core/setup_test.rb",
     "test/core/situation_test.rb",
     "test/core/teardown_test.rb",
     "test/extensions/rrriot_test.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/thumblemonks/riot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An extremely fast, expressive, and context-driven unit-testing framework. Protest the slow test.}
  s.test_files = [
    "test/benchmark/colorize.rb",
     "test/benchmark/message_concatenation.rb",
     "test/benchmark/riot_vs_minitest.rb",
     "test/benchmark/same_elements_vs_set.rb",
     "test/benchmark/simple_context_and_assertions.rb",
     "test/core/assertion_macro_test.rb",
     "test/core/assertion_macros/any_test.rb",
     "test/core/assertion_macros/assigns_test.rb",
     "test/core/assertion_macros/empty_test.rb",
     "test/core/assertion_macros/equals_test.rb",
     "test/core/assertion_macros/equivalent_to_test.rb",
     "test/core/assertion_macros/exists_test.rb",
     "test/core/assertion_macros/includes_test.rb",
     "test/core/assertion_macros/kind_of_test.rb",
     "test/core/assertion_macros/matching_test.rb",
     "test/core/assertion_macros/nil_test.rb",
     "test/core/assertion_macros/not_borat_test.rb",
     "test/core/assertion_macros/raises_test.rb",
     "test/core/assertion_macros/respond_to_test.rb",
     "test/core/assertion_macros/same_elements_test.rb",
     "test/core/assertion_macros/size_test.rb",
     "test/core/assertion_test.rb",
     "test/core/chained_context_middleware_test.rb",
     "test/core/context_middleware_test.rb",
     "test/core/context_test.rb",
     "test/core/context_with_options_test.rb",
     "test/core/message_test.rb",
     "test/core/report_test.rb",
     "test/core/setup_test.rb",
     "test/core/situation_test.rb",
     "test/core/teardown_test.rb",
     "test/extensions/rrriot_test.rb",
     "test/teststrap.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rr>, [">= 0"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 0"])
    else
      s.add_dependency(%q<rr>, [">= 0"])
      s.add_dependency(%q<term-ansicolor>, [">= 0"])
    end
  else
    s.add_dependency(%q<rr>, [">= 0"])
    s.add_dependency(%q<term-ansicolor>, [">= 0"])
  end
end

